// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6edtAC5T1Coqr0vR1WSTb7BBHcwLPgs',
    appId: '1:12996258365:web:83b829667abfcc1cd29854',
    messagingSenderId: '12996258365',
    projectId: 'moviesocialapp-a158d',
    authDomain: 'moviesocialapp-a158d.firebaseapp.com',
    storageBucket: 'moviesocialapp-a158d.firebasestorage.app',
    measurementId: 'G-9WDW0S0WGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasKPTJIidY79JyYi7eyykcLwjbXKmKKs',
    appId: '1:12996258365:android:edc9e90e5d9fccf4d29854',
    messagingSenderId: '12996258365',
    projectId: 'moviesocialapp-a158d',
    storageBucket: 'moviesocialapp-a158d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ue5Xn2Qt9nPDVNVOrF_j3Ufaq1QMqrY',
    appId: '1:12996258365:ios:a7aaddd9f49449ddd29854',
    messagingSenderId: '12996258365',
    projectId: 'moviesocialapp-a158d',
    storageBucket: 'moviesocialapp-a158d.firebasestorage.app',
    iosBundleId: 'com.example.movieSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ue5Xn2Qt9nPDVNVOrF_j3Ufaq1QMqrY',
    appId: '1:12996258365:ios:a7aaddd9f49449ddd29854',
    messagingSenderId: '12996258365',
    projectId: 'moviesocialapp-a158d',
    storageBucket: 'moviesocialapp-a158d.firebasestorage.app',
    iosBundleId: 'com.example.movieSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6edtAC5T1Coqr0vR1WSTb7BBHcwLPgs',
    appId: '1:12996258365:web:6e7baf28d3d80669d29854',
    messagingSenderId: '12996258365',
    projectId: 'moviesocialapp-a158d',
    authDomain: 'moviesocialapp-a158d.firebaseapp.com',
    storageBucket: 'moviesocialapp-a158d.firebasestorage.app',
    measurementId: 'G-5LGD6SFZ2W',
  );
}
